feat: se agrego la palabra rol
evermolina/Ejemplo pull request #10
Opened 2022-07-31 23:53 UTC by eimolina

2022-07-31 23:57 UTC, evermolina requested changes

2022-07-31 23:57 UTC, evermolina commented on index.html
> +                    <p class="card-text"><small class="text-muted">Torogoz Student Rol</small></p>
podrias agregarlo en español

2022-07-31 23:59 UTC, eimolina commented on index.html
> +                    <p class="card-text"><small class="text-muted">Torogoz Student Rol</small></p>
listo

2022-08-01 00:01 UTC, merged

2022-08-01 00:07 UTC, evermolina reviewed
Thanks